### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by sakigo9** [CodeExplainedRepo/COVID-19_TRACKER_HTML_CSS_JAVASCRIPT#1]
Getting This alert while running

**Comment by hajartaou-web** [comment]
Getting This alert while running

**Comment by CodeExplainedRepo** [comment]
The JSON file sent from the API has changed, I'm working on solving the issue.

**Comment by hajartaou-web** [comment]
> The JSON file sent from the API has changed, I'm working on solving the issue.

okey thank youu :))

**Comment by CodeExplainedRepo** [comment]
The issue has been fixed !

**Comment by sakigo9** [comment]
Thank u so much!
