### ISSUE TITLE
Receiving a TypeError

### ISSUE THREAD

**Issue by martinagabrielli** [CodeExplainedRepo/COVID-19_TRACKER_HTML_CSS_JAVASCRIPT#4]
Getting this error on page reload:
<img width="1201" alt="TypeError" src="https://user-images.githubusercontent.com/1439350/87285497-7ce79100-c4ef-11ea-993a-21c9fedae1ab.png">

**Comment by riyadh84** [comment]
I have the same problem

**Comment by MrMaskedHornet** [comment]
plzfix

**Comment by CodeExplainedRepo** [comment]
Issue solved!
